BOOKING_APPROVAL_PENDING = "PENDING"
BOOKING_APPROVAL_CONFIRMED = "CONFIRMED"
BOOKING_APPROVAL_REJECTED = "REJECTED"
BOOKING_APPROVAL_CANCELLED = "CANCELLED"

PAYMENT_METHOD_CASH = "cash"
PAYMENT_METHOD_WALLET = "wallet"
PAYMENT_METHOD_GATEWAY = "gateway"
PAYMENT_METHOD_BANK_TRANSFER = "bank_transfer"

ONLINE_PAYMENT_METHODS = {
    PAYMENT_METHOD_WALLET,
    PAYMENT_METHOD_GATEWAY,
    PAYMENT_METHOD_BANK_TRANSFER,
}

PAYMENT_STATUS_AWAITING_CASH = "AWAITING_CASH"
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_PAID = "PAID"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_EXPIRED = "EXPIRED"

FLIGHT_STATUS_WAITING_CONFIRMATION = "WAITING_CONFIRMATION"
FLIGHT_STATUS_WAITING = "WAITING"
FLIGHT_STATUS_PICKING_UP = "PICKING_UP"
FLIGHT_STATUS_EN_ROUTE = "EN_ROUTE"
FLIGHT_STATUS_FLYING = "FLYING"
FLIGHT_STATUS_LANDED = "LANDED"

PICKUP_OPTION_SELF = "self"
PICKUP_OPTION_SHUTTLE = "pickup"
