from __future__ import annotations

from typing import Protocol

from modules.catalog.domain.entities import ServiceFeature, ServicePackage
from modules.catalog.domain.payloads import ServiceFeaturePayload, ServicePackagePayload


class ServicePackageRepository(Protocol):
    def list(self, *, featured_only: bool = False, active_only: bool = True) -> list[ServicePackage]: ...
    def get_by_slug(self, slug: str) -> ServicePackage | None: ...
    def create(self, payload: ServicePackagePayload) -> ServicePackage: ...
    def update(self, slug: str, payload: ServicePackagePayload) -> ServicePackage: ...
    def delete(self, slug: str) -> None: ...
    def list_features(self, *, active_only: bool = False) -> list[ServiceFeature]: ...
    def get_feature(self, feature_id: str) -> ServiceFeature | None: ...
    def create_feature(self, payload: ServiceFeaturePayload) -> ServiceFeature: ...
    def update_feature(self, feature_id: str, payload: ServiceFeaturePayload) -> ServiceFeature: ...
    def delete_feature(self, feature_id: str) -> None: ...
