from __future__ import annotations

from datetime import datetime, timedelta
from typing import Protocol

from modules.accounts.domain.entities import Account, AuthSession
from modules.accounts.domain.payloads import AccountPayload


class AccountRepository(Protocol):
    def create(self, payload: AccountPayload, *, password_hash: str) -> Account: ...
    def get_by_id(self, account_id: str) -> Account | None: ...
    def get_by_email(self, email: str) -> Account | None: ...
    def get_by_phone(self, phone: str) -> Account | None: ...
    def list(self, *, role: str | None = None, is_active: bool | None = None) -> list[Account]: ...
    def update(self, account: Account, *, password_hash: str | None = None) -> Account: ...
    def delete(self, account_id: str) -> None: ...
    def verify_password(self, account_id: str, raw_password: str) -> bool: ...
    def create_session(self, *, account_id: str, expires_at: datetime) -> AuthSession: ...
    def revoke_session(self, token: str) -> None: ...
    def get_by_token(self, token: str) -> Account | None: ...
    def set_email_verification_token(self, *, account_id: str, token: str, sent_at: datetime) -> None: ...
    def verify_email_by_token(self, token: str, *, expires_after: timedelta) -> Account | None: ...
