# Generated by Django 5.2.7 on 2026-04-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransactiondocument_deposit_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactiondocument',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paymenttransactiondocument',
            name='qr_code_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='paymenttransactiondocument',
            name='transfer_content',
            field=models.CharField(max_length=160),
        ),
    ]
