from __future__ import annotations

from typing import Protocol

from modules.posts.domain.entities import Post
from modules.posts.domain.payloads import PostPayload


class PostRepository(Protocol):
    def list(self, *, published_only: bool = True) -> list[Post]: ...
    def get_by_slug(self, slug: str) -> Post | None: ...
    def create(self, payload: PostPayload) -> Post: ...
    def update(self, slug: str, payload: PostPayload) -> Post: ...
    def delete(self, slug: str) -> None: ...
