# Generated by Codex on 2026-04-19

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceFeatureDocument",
            fields=[
                ("id", django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "service_features",
                "ordering": ["name"],
            },
        ),
    ]
