from __future__ import annotations

from datetime import date
from typing import Protocol

from modules.bookings.domain.entities import Booking
from modules.bookings.domain.payloads import BookingPayload


class BookingRepository(Protocol):
    def create(self, payload: BookingPayload) -> Booking: ...
    def get_by_code(self, code: str) -> Booking | None: ...
    def list_by_phone(self, phone: str) -> list[Booking]: ...
    def list_by_email(self, email: str) -> list[Booking]: ...
    def list_all(self) -> list[Booking]: ...
    def list_cancelled(self) -> list[Booking]: ...
    def list_pending_review(self) -> list[Booking]: ...
    def list_confirmed(self) -> list[Booking]: ...
    def list_for_pilot(self, phone: str) -> list[Booking]: ...
    def count_reserved_for_slot(self, service_slug: str, flight_date: date, flight_time: str) -> int: ...
    def reserved_counts_for_month(self, service_slug: str, year: int, month: int) -> dict[str, dict[str, int]]: ...
    def list_assigned_pilot_phones_for_slot(
        self,
        flight_date: date,
        flight_time: str,
        *,
        exclude_code: str | None = None,
    ) -> list[str]: ...
    def update(self, booking: Booking) -> Booking: ...
